/*

Naming convention:

- FETCH_XXX           Remote asynchronous calls
- FETCH_XXX_SUCCESS   Data returned from remote calls (typically created in .then(json => ...))
- FETCH_XXX_FAILED    Failure to retrieve remote data (typically created in .catch(err => ...))
- SET_XXX             Set local state synchronously

Avoid GET_XXX in order not to confuse selectors and action creators.

*/

export const FETCH_DATABASE_INFO = "FETCH_DATABASE_INFO";
export const FETCH_DATABASE_INFO_SUCCESS = "FETCH_DATABASE_INFO_SUCCESS";
export const FETCH_DATABASE_INFO_FAILED = "FETCH_DATABASE_INFO_FAILED";

export const FETCH_DEVICE_NAMES = "FETCH_DEVICE_NAMES";
export const FETCH_DEVICE_NAMES_SUCCESS = "FETCH_DEVICE_NAMES_SUCCESS";
export const FETCH_DEVICE_NAMES_FAILED = "FETCH_DEVICE_NAMES_FAILED";

export const FETCH_DEVICE = "FETCH_DEVICE";
export const FETCH_DEVICE_SUCCESS = "FETCH_DEVICE_SUCCESS";
export const FETCH_DEVICE_FAILED = "FETCH_DEVICE_FAILED";

export const SET_CURRENT_DEVICE = "SET_CURRENT_DEVICE";
export const SET_SEARCH_FILTER = "SET_SEARCH_FILTER";
export const SET_DATA_FORMAT = "SET_DATA_FORMAT";

export const DISPLAY_ERROR = "DISPLAY_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const DEVICE_STATE_RECEIVED = "DEVICE_STATE_RECEIVED";
export const ATTRIBUTE_FRAME_RECEIVED = "ATTRIBUTE_FRAME_RECEIVED";

export const FETCH_LOGGED_ACTIONS = "FETCH_LOGGED_ACTIONS";
export const FETCH_LOGGED_ACTIONS_SUCCESS = "FETCH_LOGGED_ACTIONS_SUCCESS";
export const FETCH_LOGGED_ACTIONS_FAILED = "FETCH_LOGGED_ACTIONS_FAILED";

export const EXECUTE_COMMAND = "EXECUTE_COMMAND";
export const EXECUTE_COMMAND_SUCCESS = "EXECUTE_COMMAND_SUCCESS";
export const EXECUTE_COMMAND_FAILED = "EXECUTE_COMMAND_FAILED";

export const ENABLE_DISPLEVEL = "ENABLE_DISPLEVEL";
export const DISABLE_DISPLEVEL = "DISABLE_DISPLEVEL";
export const ENABLE_ALL_DISPLEVEL = "ENABLE_ALL_DISPLEVEL";

export const SET_DEVICE_PROPERTY = "SET_DEVICE_PROPERTY";
export const SET_DEVICE_PROPERTY_SUCCESS = "SET_DEVICE_PROPERTY_SUCCESS";
export const SET_DEVICE_PROPERTY_FAILED = "SET_DEVICE_PROPERTY_FAILED";

export const SET_DEVICE_ATTRIBUTE = "SET_DEVICE_ATTRIBUTE";
export const SET_DEVICE_ATTRIBUTE_SUCCESS = "SET_DEVICE_ATTRIBUTE_SUCCESS";
export const SET_DEVICE_ATTRIBUTE_FAILED = "SET_DEVICE_ATTRIBUTE_FAILED";

export const DELETE_DEVICE_PROPERTY = "DELETE_DEVICE_PROPERTY";
export const DELETE_DEVICE_PROPERTY_SUCCESS = "DELETE_DEVICE_PROPERTY_SUCCESS";
export const DELETE_DEVICE_PROPERTY_FAILED = "DELETE_DEVICE_PROPERTY_FAILED";

