before_script:
  - docker info

build_image:
  stage: build
  script:
    - docker build . -t docker.maxiv.lu.se/webjive-frontend
    - docker push docker.maxiv.lu.se/webjive-frontend
  only:
    - master

deploy_image:
  stage: deploy
  script:
  - 'curl -H "Authorization: Bearer $AWX_TOKEN" -XPOST https://ansible.maxiv.lu.se/api/v2/job_templates/33/launch/'
  only:
    - master
