before_script:
  - docker info

build_image:
  script:
    - docker build . -t docker.maxiv.lu.se/webjive-frontend
    - docker push docker.maxiv.lu.se/webjive-frontend
  only:
    - master
    
build_image:
  when: on_success
  script:
  - curl -k --request POST https://ansible.maxiv.lu.se/api/v2/job_templates/6/launch/