before_script:
  - docker info

deploy_image:
  script:
  - curl -k -H "Authorization: Bearer gOj9o8s3RapHiThfNbImaFYMDoOKTG" --request POST https://ansible.maxiv.lu.se/api/v2/job_templates/6/launch/
  only:
    - master
