export const OPEN_LOGIN_DIALOG = "OPEN_LOGIN_DIALOG";
export const CLOSE_LOGIN_DIALOG = "CLOSE_LOGIN_DIALOG";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const PRELOAD_USER = "PRELOAD_USER";
export const PRELOAD_USER_SUCCESS = "PRELOAD_USER_SUCCESS";
export const PRELOAD_USER_FAILED = "PRELOAD_USER_FAILED";

export const EXTEND_LOGIN = "EXTEND_LOGIN";
export const EXTEND_LOGIN_SUCCESS = "EXTEND_LOGIN_SUCCESS";
export const EXTEND_LOGIN_FAILED = "EXTEND_LOGIN_FAILED";
