export const SELECT_WIDGETS = "SELECT_WIDGETS";
export const DELETE_WIDGET = "DELETE_WIDGET";
export const ADD_WIDGET = "ADD_WIDGET";
export const MOVE_WIDGETS = "MOVE_WIDGET";
export const RESIZE_WIDGET = "RESIZE_WIDGET";

export const SET_INPUT = "SET_INPUT";
export const ADD_INPUT = "ADD_INPUT";
export const DELETE_INPUT = "DELETE_INPUT";

export const SELECT_CANVAS = "SELECT_CANVAS";

export const TOGGLE_MODE = "TOGGLE_MODE";

export const PRELOAD_DASHBOARD = "PRELOAD_WIDGETS";

export const DASHBOARDS_LOADED = "DASHBOARDS_LOADED";
