export const UNDO = "UNDO"
export const REDO = "REDO"

export const SELECT_WIDGETS = "SELECT_WIDGETS";
export const DELETE_WIDGET = "DELETE_WIDGET";
export const ADD_WIDGET = "ADD_WIDGET";
export const MOVE_WIDGETS = "MOVE_WIDGET";
export const RESIZE_WIDGET = "RESIZE_WIDGET";

export const SET_INPUT = "SET_INPUT";
export const ADD_INPUT = "ADD_INPUT";
export const DELETE_INPUT = "DELETE_INPUT";

export const SELECT_CANVAS = "SELECT_CANVAS";

export const TOGGLE_MODE = "TOGGLE_MODE";

export const SAVE_DASHBOARD="SAVE_DASHBOARD"
export const DASHBOARD_SAVED="DASHBOARD_SAVED"

export const LOAD_DASHBOARD = "LOAD_DASHBOARD";
export const DASHBOARD_LOADED = "DASHBOARD_LOADED";

export const LOAD_DASHBOARDS = "LOAD_DASHBOARDS";
export const DASHBOARDS_LOADED = "DASHBOARDS_LOADED";

export const RENAME_DASHBOARD = "RENAME_DASHBOARD";
export const DASHBOARD_RENAMED = "DASHBOARD_RENAMED";

export const DELETE_DASHBOARD = "DELETE_DASHBOARD";
export const DASHBOARD_DELETED = "DASHBOARD_DELETED";

export const CLONE_DASHBOARD = "CLONE_DASHBOARD";
export const DASHBOARD_CLONED = "DASHBOARD_CLONED";

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";

export const DASHBOARD_CREATED = "DASHBOARD_CREATED";


